### PR TITLE
Bump boolector-sys to 0.5.0

### PR DESCRIPTION
**Pull request by inspier**

### CODE REVIEW

**Comment by cdisselkoen** [comment]
Looks like a lot of this PR is essentially a `cargo fmt` - do you mind if I just commit a `cargo fmt` to master and then you can rebase on that?

**Comment by inspier** [comment]
Yeah that's fine.

**Comment by cdisselkoen** [comment]
Done - feel free to rebase

**Comment by inspier** [comment]
Sorry for the delay.

**Comment by cdisselkoen** [comment]
Haha no, thanks for the prompt reply.  And thanks for the contribution!

**Pull request merged**
